# Generated by Django 4.2 on 2024-11-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre en SAP')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre receta')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='ingredientes')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('categories', models.ManyToManyField(blank=True, null=True, related_name='categories', to='recetas.category', verbose_name='categorias')),
            ],
        ),
        migrations.CreateModel(
            name='ImageRecipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='recipes')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recetas.recipe', verbose_name='Imagen Receta')),
            ],
        ),
    ]
