# Generated by Django 4.2 on 2024-11-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='imagerecipe',
            options={'managed': True, 'verbose_name': 'Image Recipe', 'verbose_name_plural': 'Image Recipes'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'managed': True, 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.CreateModel(
            name='CombinedRecipes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipe1', to='recetas.recipe', verbose_name='receta 1')),
                ('recipe2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipe2', to='recetas.recipe', verbose_name='receta 2')),
            ],
        ),
    ]
