# Generated by Django 4.2 on 2024-11-18 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recetas', '0002_alter_category_options_alter_imagerecipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combinedrecipes',
            options={'managed': True, 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'managed': True, 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autor', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
