# Generated by Django 4.2 on 2024-11-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_alter_combinedrecipes_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, upload_to='categories'),
            preserve_default=False,
        ),
    ]
